
[servers]

worker-node-1-ansible ansible_host=51.21.212.89
worker-node-2-ansible ansible_host=13.50.166.75
worker-node-1-ansible ansible_user=ubuntu
worker-node-2-ansible ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=/home/ubuntu/ansible-master-key
ansible_python_interpreter=/usr/bin/python3
