#SPDX-License-Identifier: MIT-0
---
# tasks file for role/docker

- name: update system
  apt:
    name: "*"
    state: latest

- name: Install Docker
  apt:
    name: docker.io
    state: latest

- name: Add users to docker
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: Restart Docker
  service:
    name: docker
    state: restarted

- name: Register Docker Version
  command: docker --version
  register: docker_version

- name: Show Docker Version
  debug:
    msg: "{{ docker_version }}"
