- name: Setup Nginx with custom file
  hosts: servers
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy the custom html file
      copy:
        src: index.html
        dest: /var/www/html

    - name: Restart Nginx
      service:
        name: nginx
        state: reloaded

    - name: Enable Nginx
      systemd_service:
        name: nginx
        enabled: true
