- name: Show Secrets
  hosts: servers
  become: yes

  vars_files:
    - secrets.yml

  tasks:
    - name: Show Password
      debug:
        msg: "My password is {{ password }}"

    - name: Show API key
      debug:
        msg: "My API key is {{ api_key }}"
